Blog/ViewModels/EditPostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Blog.Models.Blog;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Blog.ViewModels
{
    public class EditPostViewModel
    {
        public const int MAXDESCRIPTION = 3000;
        public const int MAXBODY = 100000;

       
        [Range(1, int.MaxValue, ErrorMessage = "At least one tag can be checked")]
        public int PostTagsCount { get; set; }

        [Range(1, MAXDESCRIPTION, ErrorMessage = "Description charachers count must be between 1 and 3000")]
        public int DescriptionCounter { get; set; }

        [Range(1, MAXBODY, ErrorMessage = "Body charachers count must be between 1 and 100000")]
        public int BodyCounter { get; set; }

        public Post Post { get; set; }
        public IEnumerable<PostTagViewModel> Tags { get; set; }
    }
}

Blog/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Repositories;
using Blog.Repositories.Blog;
using Blog.Models.Blog;
using Blog.ViewModels;
using Blog.Filters;
using Blog.Models.Visitor;

namespace Blog.Controllers
{
    public class BlogController : Controller
    {
       public const int PostsPerPage = 10;
       private IBlogRepository<Post, int> _repo;

       public BlogController(IBlogRepository<Post, int> repo)
       {
           _repo = repo;
       }


       public ActionResult GetBlogPage(string id)
       {
           var description = id;
           var page = _repo.GetBlogPage(description);
           if (Request.IsAjaxRequest())
           {
               return Json(page , JsonRequestBehavior.AllowGet);
           }

           else
           {              
               return View(page);
           }

       }


        public ActionResult GetPosts(int id = 1, int postsPerPage = PostsPerPage)
        {
            var page = id;
            var vm = _repo.GetPosts(page, postsPerPage);
            
            vm.PageNumber = page;
            var IsAuthenticated = User.Identity.IsAuthenticated;
                          

            if (Request.IsAjaxRequest())
            {
                return Json(new
                {
                    CurrentPage = page,
                    PagesCount = vm.PagesCount,
                    PostsPerPage = PostsPerPage,
                    NextPage = page == vm.PagesCount ? page : page + 1,
                    PrevPage = page == 1 ? page : page - 1,
                    IsNext = page == vm.PagesCount,
                    IsPrev = page == 1,                    
                    IsAuthenticated = User.Identity.IsAuthenticated,

                    Posts = vm.Posts.Select(p => new
                    {
                        Id = p.Id,
                        Title = p.Title,
                        PostedOn = p.PostedOn.ToString("dd-MMM-yyyy"),
                        Description = p.Description,
                        CommentsCount = p.CommentsCount,
                        IsAuthenticated = IsAuthenticated,
                        PostDislikesCount = p.PostDislikesCount,
                        PostLikesCount = p.PostLikesCount,
                        Tags = p.Tags.Select(pp => new { Id = pp.Id, Name = pp.Name }).OrderBy(k => k.Name)
                    }).ToList()
                }, JsonRequestBehavior.AllowGet);
           
            }

            else
            {
                vm.Tags = _repo.GetTags();
                return View(vm);
            }
            
        }

        [AllowAnonymous]
        [VisitorActionFilter(ActionType = (int)ActionType.SeeBlog, PostId = "id")]
        public ActionResult GetPost(int id)
        {
            var post = _repo.GetPost(id);
 
            if (post.CommentsCount > 0)
            {
                var comments = post.Comments.ToList();
                var commentsSorted = new List<Comment>();
                var comment = comments.Where(r => r.ParentCommentId == null).FirstOrDefault();

                while (comment != null) {
                    commentsSorted.Add(comment);
                    comment = comments.Where(r => r.ParentCommentId == comment.Id).FirstOrDefault();
                }
                post.Comments = commentsSorted;

            }
            
            if (Request.IsAjaxRequest())
            {
                return Json(
                            new
                             {
                                 post = new
                                       {
                                           Id = post.Id,
                                           Title = post.Title,
                                           PostedOn = post.PostedOn.ToString("dd-MMM-yyyy"),
                                           Description = post.Description,
                                           Body = post.Body,
                                           IsAuthenticated = User.Identity.IsAuthenticated,
                                           NextPostId = post.NextPostId,
                                           PrevPostId = post.PrevPostId,
                                           PageNumber = post.PageNumber,
                                           PostsCount = post.PostsCount,
                                           Tags = post.Tags.Select(pp => new { 
                                               Id = pp.Id, 
                                               Name = pp.Name 
                                           }),
                                           Comments = post.Comments.Select(c => new {
                                               CommentBody = c.CommentBody,
                                               PostedOn = c.PostedOn.ToString("dd-MMM-yyyy"),
                                               UserName = c.UserName 
                                           }),
                                           CommentsCount = post.CommentsCount,
                                           PostDislikesCount =post.PostDislikesCount,
                                           PostLikesCount = post.PostLikesCount,
                                       }
                             },
                               JsonRequestBehavior.AllowGet);
            }
            else return View(post);
        }

        [AllowAnonymous]
       // [VisitorActionFilter(ActionType = (int)ActionType.SeeBlog, TagId = "id")]
        //[AcceptVerbs(HttpVerbs.Post)]
        public ActionResult GetPostsByTag(int id , int page = 1,  int postsPerPage =  PostsPerPage)
        {
            var vm = _repo.GetPostsByTag(id, page, postsPerPage);
            var IsAuthenticated = User.Identity.IsAuthenticated;
            return Json(
         new
           {
               CurrentPage = page,
               PagesCount = vm.PagesCount,
               PostsPerPage = PostsPerPage,
               NextPage = page == vm.PagesCount ? page : page +1,
               PrevPage = page == 1 ? page : page - 1,
               IsNext = page == vm.PagesCount,
               IsPrev = page == 1,
               TagId = id,
               IsAuthenticated = User.Identity.IsAuthenticated,

               Posts = vm.Posts.Select(p => new { 
                   Id = p.Id, 
                   Title = p.Title, 
                   PostedOn = p.PostedOn.ToString("dd-MMM-yyyy"),
                   Description = p.Description,
                   CommentsCount = p.CommentsCount,
                   IsAuthenticated = IsAuthenticated,
                   PostDislikesCount = p.PostDislikesCount,
                   PostLikesCount = p.PostLikesCount,
                   Tags= p.Tags.Select(pp => new {Id= pp.Id, Name = pp.Name}).OrderBy(k => k.Name)}).ToList()
           },
           JsonRequestBehavior.AllowGet);
        }



     //  [AcceptVerbs(HttpVerbs.Post)]
       public ActionResult ExpandPost(int id)
       {
           var post = _repo.ExpandPost(id);
           return Json(
            new
            {
                  Body = post == null ? "Post body was not found" : post.Body,
            },
          JsonRequestBehavior.AllowGet);
       }



      // [ChildActionOnly]
       public ActionResult GetTags()
       {
           var tags = _repo.GetTags();
            if (Request.IsAjaxRequest())
            {
                return Json(
                            tags.OrderBy(t => t.Name).ToList(),
                                    JsonRequestBehavior.AllowGet);
           }
           else
           return PartialView("_Tags", tags);
       }

       [ChildActionOnly]
       public ActionResult GetTagsWithCount()
       {

           var tags = _repo.GetTagsWithUsedCount();

           return PartialView(tags);
       }



       [ValidateInput(false)]
       [AcceptVerbs(HttpVerbs.Post)]
       public ActionResult AddComment(Comment comment)
       {
          var userName = User.Identity.Name;
          var IpAddress = HttpContext.Request.UserHostAddress;
          comment.UserName = (userName != null && userName != "") ? userName : "Anonymous IP: " + IpAddress;
          comment.PostedOn = DateTime.Now;

          var commentSaved = _repo.AddComment(comment);
          return Json(
          new
          {
              comment = new { 
                  Id = commentSaved.Id, 
                  UserName = commentSaved.UserName,
                  PostedOn = commentSaved.PostedOn.ToString("dd-MMM-yyyy"),
                  CommentBody = commentSaved.CommentBody,
                  CommetnsCount = commentSaved.Post.CommentsCount
              }
          },
          JsonRequestBehavior.AllowGet);
       }


     //  [AcceptVerbs(HttpVerbs.Post)]
       public ActionResult AddPostLike(int id, bool like = true)
       {
           var userName = User.Identity.Name;
           int result = 0;
           if (userName != null && userName != "")
               result = _repo.AddPostLike(id, userName, like);
           return Json(
            new
            {
                result = result
            },
          JsonRequestBehavior.AllowGet);
       }


        [VisitorActionFilter(ActionType = (int)ActionType.SeeWhoLikes, PostId = "id")]
      // [AcceptVerbs(HttpVerbs.Post)]
       public ActionResult GetNamesWhoLike(int id, bool like = true)
       {


           var result = _repo.GetNamesWhoLike(id,  like);
           return Json(
            new
            {
                likeordislike = like? "Like" :"Dislike",
                numbertoshow = 40,
                count = result.Count(), 
                usernames = result.ToArray()
            },
          JsonRequestBehavior.AllowGet);
       }

       

    }
}

Blog/Views/Admin/EditPost.cshtml
@model EditPostViewModel
@using Microsoft.AspNet.Identity;
@using Blog.ViewModels;

@{
    
    var i = 0;
    
}


   

@section MainContent{


    @using (Html.BeginForm("InsertOrUpdatePost", "Admin"))
    {  <div class="form-group">
        @Html.AntiForgeryToken()        
        @Html.HiddenFor(m => m.Post.Id)

        <div class="row" style="margin-bottom:50px;">

            <div class="col-xs-12 text-left">
                @Html.LabelFor(m => m.Post.Title) @Html.ValidationMessageFor(m => m.Post.Title)
            </div>


            <div class="col-xs-12">
                @Html.TextAreaFor(m => m.Post.Title, new { @class = "form-control" })
            </div>


        </div>



        <div class="row " style="margin-bottom:30px;">
            <div class=" col-xs-12">
                @Html.LabelFor(m => m.Post.Description) @Html.ValidationMessageFor(m => m.DescriptionCounter)
                <div class="input-group" style="margin-bottom:1px;">
                    <span class="input-group-addon"> Html │ Max │ @EditPostViewModel.MAXDESCRIPTION │  Entered </span>
                    @Html.TextBoxFor(m => m.DescriptionCounter, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>
            <div class=" col-xs-12">
                @Html.EditorFor(m => m.Post.Description)

            </div>
        </div>


        <div class="row" style="margin-bottom:30px;">
            <div class=" col-xs-12">
                @Html.LabelFor(m => m.Post.Body) @Html.ValidationMessageFor(m => m.BodyCounter)
                <div class="input-group" style="margin-bottom:1px;">
                    <span class="input-group-addon"> Html │ Max │ @EditPostViewModel.MAXBODY │  Entered </span>
                    @Html.TextBoxFor(m => m.BodyCounter, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>
            <div class=" col-xs-12">
                @Html.EditorFor(m => m.Post.Body)
            </div>
        </div>

        <div class="row" style="margin-bottom:30px;">
            <div class="col-md-12">
                @Html.LabelFor(m => m.Tags)

                @Html.ValidationMessageFor(m => m.PostTagsCount)
                <div class="input-group" style="margin-bottom:1px;">
                    <span class="input-group-addon">  Checked </span>
                    @Html.TextBoxFor(m => m.PostTagsCount, new { @readonly = "readonly", @class = "form-control" })
                </div>

            </div>
            <div class="col-md-12">
                <div style="border: solid 1px lightgray; padding: 12px 12px">
                    <div class="row">
                        @foreach (var tag in Model.Tags)
                        {
                            var controlName = "Post.Tags[" + i++ + "].Id";
                            
                            <div class="col-xs-6 col-lg-3 col-sm-4">
                                <label class="checkbox-inline">
                                    @Html.CheckBox(controlName, tag.Checked, new { value = tag.Id, @class = "check-tag" }) @tag.Name
                                </label>
                            </div>
                        }

                    </div>

                </div>

            </div>
        </div>

           <div class="row" style="margin-bottom:30px;">

               <div class="col-xs-12">
                   <div style="border: solid 1px lightgray; padding: 12px 12px">
                       <label class="checkbox-inline">
                           @Html.CheckBoxFor(m=>m.Post.Published) Published
                       </label>
                   </div>
                   </div>

           </div>



        <div class="row" style="margin-top:40px;">
            <div class=" col-xs-12 text-center ">
                <div class="btn-group ">
                    <button type="submit" class="btn btn-primary " id="btnsave">Save</button>
                    <a class="btn   btn-default  link-delete-post"
                       href="@Url.Action( "GetPosts", "Admin")" title="Cancel">
                        Cancel
                    </a>
                </div>
            </div>

        </div>
    </div>

    }
}



@section RightSideContent{
    
}

@section Scripts{
<script src="http://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
<script type="text/javascript" src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
@Scripts.Render("~/Scripts/jquery.validate.min.js")
@Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
<!-- jquery tinymce library -->
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    
    <script>
    $(document).ready(function () {

        $.validator.setDefaults({ ignore: "" });

        $('.btn').button();

        tinymce.init({
            selector: '#Post_Description',

            charLimit: @EditPostViewModel.MAXDESCRIPTION,
            setup: function(editor) {
                editor.on('keyup', function (e) {
                    updateTinyMiceHtmlCounter(editor, e, "#DescriptionCounter")
                });
                editor.on('loadcontent', function (e) {
                    updateTinyMiceHtmlCounter(editor, e, "#DescriptionCounter")
                });
            },

            height: 200,
            theme: 'modern',
            plugins: [
              'advlist autolink lists link image charmap print preview hr anchor pagebreak',
              'searchreplace wordcount visualblocks visualchars code fullscreen',
              'insertdatetime media nonbreaking save table contextmenu directionality',
              'emoticons template paste textcolor colorpicker textpattern imagetools'
            ],
            toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons',
            image_advtab: true,

            templates: [
              { title: 'Test template 1', content: 'Test 1' },
              { title: 'Test template 2', content: 'Test 2' }
            ],
            content_css: [
              '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
              '//www.tinymce.com/css/codepen.min.css'
            ]
        });


        tinymce.init({
            selector: '#Post_Body',
            charLimit: @EditPostViewModel.MAXBODY,
            setup: function(editor) {
                editor.on('keyup', function (e) {
                    updateTinyMiceHtmlCounter(editor, e, "#BodyCounter")
                });
                editor.on('loadcontent', function (e) {
                    updateTinyMiceHtmlCounter(editor, e, "#BodyCounter")
                });
            },



            height: 500,
            theme: 'modern',
            plugins: [
              'advlist autolink lists link image charmap print preview hr anchor pagebreak',
              'searchreplace wordcount visualblocks visualchars code fullscreen',
              'insertdatetime media nonbreaking save table contextmenu directionality',
              'emoticons template paste textcolor colorpicker textpattern imagetools'
            ],
            toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons',
            image_advtab: true,
            templates: [
              { title: 'Test template 1', content: 'Test 1' },
              { title: 'Test template 2', content: 'Test 2' }
            ],
            content_css: [
              '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
              '//www.tinymce.com/css/codepen.min.css'
            ]
        });


        function updateTinyMiceHtmlCounter(ed, e, inputCopyIdentifier) {
            var  tinylen, htmlcount;
            tinylen = ed.getContent().length;
            $(inputCopyIdentifier).val(tinylen);
        }

        $(".check-tag").change( function () {

            var control = $('#PostTagsCount');
            var value =  parseInt(control.val());

            if ($(this).is(':checked') )
            {
                control.val(++value);
            }
            else
            {
                control.val(--value);
            }
        });

    });
</script>
}

Blog/Views/Admin/GetPosts.cshtml
@using Blog.ViewModels;
@using Blog.Models.Blog;
@model IEnumerable<PostShortViewModel>

@{
    ViewBag.Title = "Index";
    
    
}


@section MainContent{

    <div id="listBody" style="margin-top:40px;">


        <div class="row">

            <div class="col-xs-12 col-sm-5 hidden-xs"> <b>Title</b></div>
            <div class="col-xs-1 col-sm-2 hidden-xs"> <b>Published</b></div>
            <div class="col-xs-12 col-sm-3 hidden-xs"> <b>Tags</b></div>


            <div class="col-xs-12 col-sm-2">
                <div class="btn-group ">
                    <a class="btn btn-sm  btn-default  link-edit-post"
                       href="@Url.Action("EditPost", "Admin")" title="Add a new post">
                        <span class="glyphicon glyphicon-plus"></span>
                    </a>
                    <button class="btn btn-default btn-sm btn-refresh-posts" title="Refresh posts" type="button">
                        <span class="glyphicon glyphicon-refresh"></span>
                    </button>
                </div>
            </div>
        </div>
        <hr id="hr-posts" />

        @foreach (var post in Model)
        {
            <div class="row">
                <div class="col-xs-12 col-sm-5">                    
                  @Html.ActionLink(post.Title, "GetPost", "Blog", new { id = post.Id }, new { @class = "post-title" })                    
                </div>
                <div class="col-xs-1 col-sm-2 ">
                    @post.PostedOn<br/> 
                    <input type="checkbox" class="checkbox-grid" @(post.Published? "checked ='checked'" : "")/>
                </div>
               
                <div class="col-xs-12 col-sm-3"> @post.Tags</div>

                <div class="col-xs-12 col-sm-2 ">
                    <div class="btn-group ">                        
                        <a class="btn btn-sm  btn-default  link-edit-post"
                           href="@Url.Action("EditPost", "Admin", new { id = post.Id })" title="Edit post">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a class="btn btn-sm  btn-default  link-delete-post"
                           href="@Url.Action( "DeletePost", "Admin", new { id = post.Id })" title="Delete post">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    </div>

                </div>
            </div>
            <hr />
        }
    </div>


    <!-- Modal -->
    <div class="modal fade" id="frmPostModal" role="dialog">
        <div class="modal-dialog">
            Html.Partial("EditPostModal", new Post())
        </div>
    </div>

}

@section Scripts {
    <script src="http://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
    <script type="text/javascript" src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
      <!-- jquery tinymce library -->
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>


    <script>
        $(function () {

            //---------------------------
            $(".container").on("click", ".btn-refresh-posts", function (event) {
                event.preventDefault();
                //clear search control
                var target = $("#hr-posts");
                var jqxhr = $.post("/Admin/GetPostsShortAjax", function (data) {

                    //delete old rows
                    var controlsToDelete = $(".link-delete-post").closest(".row");
                    controlsToDelete.next().remove();
                    controlsToDelete.remove();

                    // template, add new rows
                    var newControl = $("#tmpPosts").tmpl(data);
                    target.after(newControl);
                })
                .fail(function (xhr, textStatus, errorThrown) {
                    alert("Error  " + xhr.responseText);
                });

                return;
            });

            //---------------------------
            $(".container").on("click", ".btn-save-post", function (event) {

                var form = $(this).closest('form');


                form.validate();
                 if (!form.valid()) { return false };

                        $.post("/Admin/InsertOrUpdatePost", form.serialize(), function (data) {

                            var dt = data.post;
                            if (dt.Id == 0) {
                                alert("Error at server");

                            }
                            else {

                                var dt = data.post;

                                if ($("#Id").val() != '0') //if update tag
                                {

                                    //find row for update
                                    $(".link-delete-tag").each(function () {

                                        if ($(this).attr("href").split('/')[3] == dt.Id) {
                                            var target = $(this).closest('.row');

                                            target.find(".span-post-title").text(dt.Name);

                                        };
                                    });
                                }
                                else //if add new tag
                                {
                                    //insert new row
                                    var newControl = $("#tmpPosts").tmpl({ "posts": [dt] });
                                    $("#hr-posts").after(newControl);
                                }
                            }
                        });

                        $('#frmPostModal').modal('toggle');
                        return false;

            });

            //---------------------------
            $(".container").on("click", ".link-delete-post", function (event) {
                event.preventDefault();

                var deleteLinkObj = $(this);
                var parent = deleteLinkObj.closest('.row');
                var name = parent.find(".post-title").text();

                var temp = "<div id ='divModalDelete'>Do you want to delete post \"" + name + "\"?</div>";


                BootstrapDialog.show({
                    title: 'Confirmation',
                    message: temp,

                    buttons: [{
                        label: 'Yes',
                        action: function (dialogItself) {

                            $.post(deleteLinkObj[0].href, function (data) {
                                if (data.result > 0) {
                                    parent.next().remove();
                                    parent.remove();
                                    dialogItself.close();
                                }
                                else {

                                    dialogItself.close();
                                    temp.find("#divModalDelete").html("Not able to delete post\"" + name+"\"").addClass("text-danger");
                                    var dialogInstance1 = new BootstrapDialog({
                                        title: 'Error',
                                        type: BootstrapDialog.TYPE_DANGER,
                                        message: temp.html()
                                    });
                                    dialogInstance1.open();
                                }

                            });
                        }

                    }, {
                        label: 'No',
                        action: function (dialogItself) {
                            dialogItself.close();
                        }
                    }]
                });


            });

            //------------------------------
            $(".container").on("click", ".btn-add-post", function (event) {
                event.preventDefault();
                //clear errors
                var form = $("#frmPostModal").find('form');
                $inputs = form.find("input").removeClass("input-validation-error");
                $('.field-validation-error').empty();

                $("#Id").val("0");
                $("#Title").val("");
                $("#Description").val("");
                $("#Body").val("");
                
                $.post("/Admin/GetTagsForNewPost", function (data) {
                    var newControl = $("#tmpPostTags").tmpl(data);
                    $("#div-post-tags").empty().append(newControl);
                });

                $(".modal-title").text("New post");
                $("#div-info").empty();
                $("#frmPostModal").modal('show');
                return false;
            });

            //---------------------------
            $(".container").on("click", ".link-edit-post-ajax", function (event) {
                event.preventDefault();

                //clear errors
                var form = $("#frmPostModal").find('form');
                $inputs = form.find("input").removeClass("input-validation-error");
                $('.field-validation-error').empty();

                var linkObj = $(this);
                var parent = linkObj.closest('.row');
                var name = parent.find(".span-tag-name").html();

                $.post(linkObj[0].href, function (data) {
                    var dt = data.post;
                    $("#Id").val(dt.Id);
                    $("#Title").val(dt.Title);
                    $("#Description").val(dt.Description);
                    $("#Body").val(dt.Body);

                    var newControl = $("#tmpPostTags").tmpl(dt);                 
                    $("#div-post-tags").empty().append(newControl);

                    $(".modal-title").text("Edit post");
                    $("#frmPostModal").modal('show');
                });
                return false;
            });
            
            
            //----------------------------------
            //to display readonly checkboxes
            $(".container").on("click", ".checkbox-grid", function (event) {
                return false;
                
            })

            //----------------------------------
            $(".container").on("click", ".btn-preview-post", function (event) {
                return false;

            })
            //----------------------------------
        })
    </script>





    <script type="text/html" id="tmpPosts">
        {{each posts}}
        <div class="row">
            <div class="col-xs-12 col-sm-5">
                <a href="/Blog?GetPost/${Id}" class="post-title">${Title}</a>
            </div>
            <div class="col-xs-12 col-sm-2 ">
                ${PostedOn}<br />
                <input type="checkbox" class="checkbox-grid" {{if Published}} ? checked ='checked' {{/if}} />
            </div>
            <div class="col-xs-12 col-sm-3 ">
                ${Tags}        
            </div>
            <div class="col-xs-12 col-sm-2">
                <div class="btn-group ">
                    <a class="btn btn-sm  btn-default link-edit-post"
                       href="/Admin/EditPost/${Id}" title="Edit post">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a class="btn btn-sm  btn-default  link-delete-post"
                       href="/Admin/DeletePost/${Id}" title="Delete post">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                </div>
            </div>
        </div>
        <hr />
        {{/each}}
    </script>



<script type="text/html" id="tmpPostTags">
    {{each Tags}}
    <div class="col-xs-12 col-sm-6 col-md-4">
        <label>
            <input type="checkbox" value="${Id}" class="checkbox-post-tag" {{if Checked}} ? checked='checked' {{/if}}> ${Name}
        </label>
    </div>
    {{/each}}
</script>
}