Blog/Models/Visitor/ActionType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.Models.Visitor
{
    public enum ActionType
    {
        Report = 1, Blog = 2,   WhoLikes= 4, See = 128, Log = 256,
        

        SeeBlog = 2 + 128,
        SeeWhoLikes = 128 + 4,
        

        
    }
}

Blog/Models/Visitor/ArxiveVisitor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Blog.Models.Visitor
{
    public class ArxiveVisitor
    {
        [Key]
        public int Id { get; set; }
        public int VisitorsCount { get; set; }
        public int UsersCount { get; set; }
        public DateTime Date { get; set; }
    }
}

Blog/Models/Visitor/ArxiveVisitorLog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.Models.Visitor
{
    public class ArxiveVisitorLog
    {
        public long Id { get; set; }
        public DateTime StartDateTime { get; set; }
        public DateTime EndDateTime { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int PostId { get; set; }
        public string UserName { get; set; }
        public long SpentTimeMC { get; set; }
        public long CountVisits { get; set; }
        public long CountUsers { get; set; }
        public long CountAnonymous { get; set; }
        public long ExitCount { get; set; }
        public long BounceCount { get; set; }
    }
}

Blog/Models/Visitor/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.Models.Visitor
{
    public class Country
    {
        public string Id { get; set; }
        public string Name { get; set; }
       
        virtual public IEnumerable<WebVisitor> Visitors { get; set; }
    }
}

Blog/Models/Visitor/GeoLocation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.Models.Visitor
{
    public class GeoLocation
    {
        public string ip { get; set; }
        public string country_code { get; set; }
        public string country_name { get; set; }
        public string region_code { get; set; }
        public string city { get; set; }
        public string zip_code { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public int metro_code { get; set; }
    }
}

Blog/Models/Visitor/OnlineVisitorsContainer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Collections.Concurrent;
using Blog.Models.Visitor;

namespace Blog.Models.Visitor
{
    public class OnlineVisitorsContainer
    {
        public static readonly ConcurrentDictionary<string, WebVisitor> Visitors = new ConcurrentDictionary<string, WebVisitor>();
    }
}

Blog/Models/Visitor/VisitorActionLog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;


namespace Blog.Models.Visitor
{
    public class VisitorActionLog
    {
        public Int64 Id { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int ActionType { get; set; }
        public string IpAddress { get; set; }
        public DateTime DateTime { get; set; }
        public string VisitorUserName { get; set; }
        public string Anonymous { get; set; }
        public string SessionId { get; set; }
        public int PostId { get; set; }
        public int TagId { get; set; }

        [NotMapped]
        public TimeSpan SpentTime
        {
            get;
            set;
        }

        public long SpentTimeMC
        {
            get
            {
                return SpentTime.Ticks;
            }
            set
            {
                SpentTime = TimeSpan.FromTicks(value);
            }
        }
    }
}

Blog/Controllers/VisitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Repositories;
using Blog.Repositories.Visitor;
using Blog.Models.Visitor;
using Blog.Filters;

namespace Blog.Controllers
{
    public class VisitorController : Controller
    {
         private IVisitorRepository<ArxiveVisitor, int> _repo;

       public VisitorController(IVisitorRepository<ArxiveVisitor, int> repo)
       {
           _repo = repo;
       }

       public static void JobSaveVisitorActionLog(VisitorActionLog log)
       {
           var db = new DbContextEF();
           IVisitorRepository<ArxiveVisitor, int> repository = new VisitorRepository(db);
           var e = repository.SaveVisitorActionLog(log);
       }
        //==================================
       public ActionResult WhoIsOnline()
       {

           var visitors = OnlineVisitorsContainer.Visitors == null || OnlineVisitorsContainer.Visitors.Count() == 0 ?
                        0 : OnlineVisitorsContainer.Visitors.Count();

           return View(visitors);

       }
       //==================================================
       //[AcceptVerbs(HttpVerbs.Post)]
       [VisitorActionFilter(ActionType = (int)ActionType.Report)]
       public JsonResult GetOnlineVisitorsMap()
       {
           if (OnlineVisitorsContainer.Visitors != null)
           {

               var visitors = OnlineVisitorsContainer.Visitors;



               visitors.Values.Where(v => v.AuthUser == null || v.AuthUser == "").Count();
               var users = visitors.Values.Where(v => v.AuthUser != null && v.AuthUser != "")
                            .GroupBy(v => v.AuthUser, v => v)
                            .Select(h => new
                            {
                                username = h.Key,
                                city = h.FirstOrDefault().GeoLocation.city,
                                ip = h.FirstOrDefault().GeoLocation.ip,
                                country_name = h.FirstOrDefault().GeoLocation.country_name,
                                code = h.FirstOrDefault().GeoLocation.country_code,
                                lat = h.FirstOrDefault().GeoLocation.latitude,
                                lon = h.FirstOrDefault().GeoLocation.longitude
                            });

               var ananimouses = visitors.Values.Where(v => v.AuthUser == null || v.AuthUser == "")
                                 .Select(h => new
                                 {
                                     username = "Anonymous",
                                     city = h.GeoLocation.city,
                                     ip = h.GeoLocation.ip,
                                     country_name = h.GeoLocation.country_name,
                                     code = h.GeoLocation.country_code,
                                     lat = h.GeoLocation.latitude,
                                     lon = h.GeoLocation.longitude
                                 });

               var result = users.Union(ananimouses)
                             .OrderBy(h => h.country_name)
                             .ThenBy(h => h.city)
                             .ThenBy(h => h.username);

               var data = result.Select((d, index) => new
               {
                   name = index,
                   lat = d.lat,
                   lon = d.lon
               }).ToArray();

               var info = result.Select((d, index) => new
               {
                   index = index,
                   ip = d.ip,
                   city = d.city,
                   country_name = d.country_name,
                   code = d.code,
                   username = d.username
               }).ToArray();

               return Json(new
               {
                   data = data,
                   info = info,
                   usersCount = users.Count(),
                   ananimousesCount = ananimouses.Count()

               }

                   , JsonRequestBehavior.AllowGet);
           }

           else
               return Json(new { data = new { } }, JsonRequestBehavior.AllowGet);
       }

       //====================================================

       public ActionResult WhoIsOnlineByCountries()
       {

           var visitors = OnlineVisitorsContainer.Visitors == null ||
                            OnlineVisitorsContainer.Visitors.Count() == 0 ? 0 :
                               OnlineVisitorsContainer.Visitors.Count();

           return View(visitors);

       }
       //======================================================= 
       [AcceptVerbs(HttpVerbs.Get)]
       [VisitorActionFilter(ActionType = (int)ActionType.Report)]
       public JsonResult GetOnlineVisitorsByCountriesMap()
       {
           if (OnlineVisitorsContainer.Visitors != null)
           {

               var visitors = OnlineVisitorsContainer.Visitors;

               var users = visitors.Values
                            .Select(v => new
                            {
                                AuthUser = (v.AuthUser != null && v.AuthUser != "") ? v.AuthUser : v.Anonymous,
                                IsUser = (v.AuthUser != null && v.AuthUser != ""),
                                country_code = v.GeoLocation.country_code,
                                country_name = v.GeoLocation.country_name
                            })
                           .GroupBy(k => k.country_code, k => k)
                           .Select(h => new
                           {
                               code = h.Key,
                               name = h.FirstOrDefault().country_name,
                               usercount = h.Where(r => r.IsUser)
                                     .GroupBy(u => u.AuthUser, u => u.AuthUser).Select(k => k.Key).Count(),
                               ananimouscount = h.Where(r => !r.IsUser)
                                     .GroupBy(u => u.AuthUser, u => u.AuthUser).Select(k => k.Key).Count(),
                           });

               var result = users.Select(c => new
               {
                   code = c.code,
                   name = c.name,
                   usercount = c.usercount,
                   ananimouscount = c.ananimouscount,
                   value = c.usercount + c.ananimouscount
               }).ToArray();


               return Json(new { data = result }, JsonRequestBehavior.AllowGet);

           }
           return Json(new { data = new { } }, JsonRequestBehavior.AllowGet);
       }
        //=====================================================
       public ActionResult GetVisitsStatistics()
       {
           var date = _repo.GetHistoryVisitorsStartDate();
           return View(date);

       }
       //=====================================================
      
       [VisitorActionFilter(ActionType = (int)ActionType.Report)]
       public JsonResult GetVisitorsForMonthChart(int month = 0, int year = 0)
       {

           var date = DateTime.Now;
           month = month == 0 || month > 12 ? date.Month : month;
           year = year == 0 ? date.Year : year;

           var date1 = new DateTime(year, month, 1, 0, 0, 0);
           var date2 = date1.AddMonths(1).AddMilliseconds(-1);

           var visits = _repo.GetVisitsForMonth(date1, date2);
           var days = Enumerable.Range(1, DateTime.DaysInMonth(year, month)).ToList();

           var result = days.GroupJoin(visits,
                                        d => d, v => v.Day,
                                        (d, v) => new
                                        {
                                            Day = d,
                                            Count1 = v.Count() == 0 ? 0 : v.FirstOrDefault().Count1,
                                            Count2 = v.Count() == 0 ? 0 : v.FirstOrDefault().Count2,
                                            Count3 = v.Count() == 0 ? 0 : v.FirstOrDefault().Count3,
                                        }).OrderBy(d => d.Day).ToList();


           return Json(new
           {
               data = new
               {
                   summary = result.Where(r => r.Count1 > 0).ToList(),
                   visits = result.Select(v => v.Count1).ToArray(),
                   users = result.Select(v => v.Count2).ToArray(),
                   ananimuses = result.Select(v => v.Count3).ToArray(),
                   visitors = result.Select(v => v.Count3 + v.Count2).ToArray(),
                   days = days.ToArray(),
                   month = month,
                   year = year,
               }
           }, JsonRequestBehavior.AllowGet);
       }


       //====================================================
       public ActionResult GetHistoryVisitorsByCountry()
       {
           var date = _repo.GetHistoryVisitorsStartDate();
           return View(date);
       }
       //======================================================= 
       [AcceptVerbs(HttpVerbs.Get)]
       [VisitorActionFilter(ActionType = (int)ActionType.Report)]
       public JsonResult GetHistoryVisitorsMap(int month = 0, int year = 0)
       {

           var date = DateTime.Now;
           month = month == 0 || month > 12 ? date.Month : month;
           year = year == 0 ? date.Year : year;

           var date1 = new DateTime(year, month, 1, 0, 0, 0);
           var date2 = date1.AddMonths(1).AddMilliseconds(-1);


           var visitors = _repo.GetVisitsForMonthByCountry(date1, date2);

           var result = visitors.Select(c => new
           {
               code = c.Id2,//country code
               name = c.Title, // country name
               value = c.Count1, //visits
               visitors = c.Count2 + c.Count3,
               usercount = c.Count2,
               ananimouscount = c.Count3,             

           }).ToArray();


           return Json(

Blog/Views/Visitor/GetHistoryVisitorsByCountry.cshtml
@model DateTime
@using Blog.Models.Visitor;
@using System.Collections.Concurrent;
@using System.Web.Security;
@using System.Web;


@section Styles
{
    <link rel="stylesheet" href="/content/bootstrap-datetimepicker.min.css" />
}


@section MainContent{ 

<div class="row">
    <div class="  col-xs-12 text-left">
        <ol class="breadcrumb">
             <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
            <li class="active">Visitors</li>

        </ol>
    </div>
</div>

<div class="row">
    <div class="  col-xs-6 col-md-4 col-sm-offset-4 text-left">




        <div class="form-group">
            <div class='input-group date' id='datetimepicker1'>
                <input type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>



    </div>
</div>


<div class="row">
    <div id="containerMap2" class="col-xs-12"></div>
    
</div>
<div id="containerMap" ></div>

}




@section Scripts {
 <!-- datetimepicker  https://eonasdan.github.io/bootstrap-datetimepicker/Installing/ -->
<script type="text/javascript" src="/scripts/moment.min.js"></script>
<script type="text/javascript" src="/scripts/bootstrap-datetimepicker.min.js"></script>

<!--  map -->
<script src="https://code.highcharts.com/maps/highmaps.js"></script>
<script src="https://code.highcharts.com/maps/modules/data.js"></script>
<script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
<script src="https://code.highcharts.com/mapdata/custom/world.js"></script>
<!-- Flag sprites service provided by Martijn Lafeber, https://github.com/lafeber/world-flags-sprite/blob/master/LICENSE -->
<link rel="stylesheet" type="text/css" href="https://cloud.github.com/downloads/lafeber/world-flags-sprite/flags32.css" />


<script>

    $(function () {
        $('#datetimepicker1').datetimepicker({
            defaultDate: new Date(),
            format: 'MMMM YYYY',
            maxDate: moment().endOf("month"),
           // minDate: new Date("@Model")
        });

        fnGetStatistics(0, 0);
        

        $("#datetimepicker1").on("dp.change", function (e) {
            fnGetStatistics(e.date.format('M'), e.date.format('YYYY'));
        });
    });

    

    //---------------------------------------
    function fnGetStatistics(month, year) {
       
        
        $.get("@Url.Action("GetHistoryVisitorsMap", "Visitor")",
             { month: month, year: year }, function (result) {
                 var data = result.data.result;
                 
                 var statisticsDate = moment([parseInt(result.year), parseInt(result.month) - 1]).endOf("month");
                 var statisticsMonthName = statisticsDate.format('MMMM');

                

            // Add lower case codes to the data set for inclusion in the tooltip.pointFormat
            $.each(data, function () {
               
                this.flag = this.code.replace('UK', 'GB').toLowerCase();
            });
            
            // Initiate the chart
            $('#containerMap').highcharts('Map', {

                title: {
                    text: 'Website visitors by countries  in ' + statisticsMonthName
                },

                legend: {
                    title: {
                        text: 'visits',
                        style: {
                            color: (Highcharts.theme && Highcharts.theme.textColor) || 'black'
                        }
                    }
                },

                mapNavigation: {
                    enabled: true,
                    buttonOptions: {
                        verticalAlign: 'top'
                    }
                },

                tooltip: {
                    backgroundColor: 'white',
                    borderWidth: 2,
                    shadow: false,
                    useHTML: true,
                    padding: 3,
                    pointFormat: '<span class="f32"><span class="flag {point.flag}"></span></span> {point.name}<br/>' +                      
                        '<b>Total visits:</b> {point.value}<br/><b>Total visitors:</b> {point.visitors}<br/><b>Authenticated:</b> {point.usercount}<br/><b>Anonymous:</b> {point.ananimouscount}<br/>',

                    positioner: function () {
                        return { x: 0, y: 250 };
                    }
                },

                colorAxis: {
                    min: 1,
                    max: 1000,
                    type: 'logarithmic'
                },

                series: [{
                    data: data,
                    mapData: Highcharts.maps['custom/world'],
                    joinBy: ['iso-a2', 'code'],
                    name: 'Country Totals',
                    states: {
                        hover: {
                            color: '#BADA55'
                        }
                    }
                }]
            });
            //--------------------------
        });
    }
   
</script>




}

Blog/Views/Visitor/GetVisitorStatistics.cshtml
@using Blog.Models.User;



@section Styles
{
    <link rel="stylesheet" href="/content/bootstrap-datetimepicker.min.css" />
}







@section MainContent{

    <div class="row">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="#"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li class="active">Statistics by visited pages  (under construction)</li>

            </ol>
        </div>
    </div>

    @Html.Action("GetVisitedPages", "Visitor")
}

Blog/Views/Visitor/GetVisitsStatistics.cshtml
@model DateTime
@using Blog.Models.User;



@section Styles
{
    <link rel="stylesheet" href="/content/bootstrap-datetimepicker.min.css" />
}



@section MainContent{
 
    <div class="row">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="#"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li class="active">Statistics by visits</li>

            </ol>
        </div>
    </div>

    <div class="row">
        <div class="  col-xs-6 col-md-4 col-sm-offset-4 text-left">

            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>



        </div>
    </div>



    <div class="row row-scroll" style="margin-top:80px;">
        <div class="  col-xs-12 text-center">
            <h4>Website visits and visitors in <span id="span-month"></span> </h4>

        </div>
        <div class="  col-xs-12 text-left">
            <div id="container" style=" min-width: 120px; margin: 0 auto"></div>

        </div>
    </div>


}




@section Scripts {

    <!-- Scripts Level 1-->
    <!-- highcharts -->
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>

    <!-- datetimepicker  https://eonasdan.github.io/bootstrap-datetimepicker/Installing/ -->
    <script type="text/javascript" src="/scripts/moment.min.js"></script>
    <script type="text/javascript" src="/scripts/bootstrap-datetimepicker.min.js"></script>

    <script>



        $(function () {


            $('#datetimepicker1').datetimepicker({
                defaultDate: new Date(),
                format: 'MMMM YYYY',
                maxDate: moment().endOf("month"),
                //minDate: new Date("@Model")
            });

            fnGetStatistics(0, 0);

            $("#datetimepicker1").on("dp.change", function (e) {
                fnGetStatistics(e.date.format('M'), e.date.format('YYYY'));
            });



                $('#container').bind('mousemove touchmove touchstart', function (e) {
                    var chart,
                        point,
                        i,
                        event;

                    for (i = 0; i < Highcharts.charts.length; i = i + 1) {
                        chart = Highcharts.charts[i];
                        event = chart.pointer.normalize(e.originalEvent); // Find coordinates within the chart
                        point = chart.series[0].searchPoint(event, true); // Get the hovered point

                        if (point) {
                            point.highlight(e);
                        }
                    }
                });
                /**
                 * Override the reset function, we don't need to hide the tooltips and crosshairs.
                 */
                Highcharts.Pointer.prototype.reset = function () {
                    return undefined;
                };

                /**
                 * Highlight a point by showing tooltip, setting hover state and draw crosshair
                 */
                Highcharts.Point.prototype.highlight = function (event) {
                    this.onMouseOver(); // Show the hover marker
                    this.series.chart.tooltip.refresh(this); // Show the tooltip
                    this.series.chart.xAxis[0].drawCrosshair(event, this); // Show the crosshair
                };

                /**
                 * Synchronize zooming through the setExtremes event handler.
                 */
                function syncExtremes(e) {
                    var thisChart = this.chart;

                    if (e.trigger !== 'syncExtremes') { // Prevent feedback loop
                        Highcharts.each(Highcharts.charts, function (chart) {
                            if (chart !== thisChart) {
                                if (chart.xAxis[0].setExtremes) { // It is null while updating
                                    chart.xAxis[0].setExtremes(e.min, e.max, undefined, false, { trigger: 'syncExtremes' });
                                }
                            }
                        });
                    }
                }


                function fnGetStatistics(month, year) {
                    $.post("@Url.Action("GetVisitorsForMonthChart", "Visitor")",
                         { month: month, year: year }, function (data) {

                             $('#container').empty();
                             var statisticsDate = moment([parseInt(data.data.year), parseInt(data.data.month) - 1]).endOf("month");
                             var statisticsMonthName = statisticsDate.format('MMMM');
                             $("#span-month").text(statisticsMonthName);

                             var xData = data.data.days;

                             var datasets = [
                             {
                                 name: "Visits",
                                 data: data.data.visits,
                                 unit: "visits",
                                 type: "line",
                                 valueDecimals: 0
                             }, {
                                 name: "Visitors",
                                 data: data.data.visitors,
                                 unit: "visitors",
                                 type: "line",
                                 valueDecimals: 0
                             }, {
                                 name: "Authenticated",
                                 data: data.data.users,
                                 unit: "visitors",
                                 type: "line",
                                 valueDecimals: 0
                             },
                                {
                                    name: "Anonymous",
                                    data: data.data.ananimuses,
                                    unit: "visitors",
                                    type: "line",
                                    valueDecimals: 0
                                }];
                             // });

                             // Get the data. The contents of the data file can be viewed at
                             // https://github.com/highcharts/highcharts/blob/master/samples/data/activity.json
                             //  $.getJSON('https://www.highcharts.com/samples/data/jsonp.php?filename=activity.json&callback=?', function (activity) {
                             $.each(datasets, function (i, dataset) {

                                 // Add X values
                                 dataset.data = Highcharts.map(dataset.data, function (val, j) {

                                     return [xData[j], val];
                                 });

                                 $('<div class="chart" style=" min-width: 120px;height: 160px;">')
                                     .appendTo('#container')
                                     .highcharts({
                                         chart: {
                                             marginLeft: 40, // Keep all charts left aligned
                                             spacingTop: 20,
                                             spacingBottom: 20
                                         },
                                         title: {
                                             text: dataset.name,
                                             align: 'left',
                                             margin: 0,
                                             x: 30
                                         },
                                         credits: {
                                             enabled: false
                                         },
                                         legend: {
                                             enabled: false
                                         },
                                         xAxis: {
                                             crosshair: true,
                                             events: {
                                                 setExtremes: syncExtremes
                                             },
                                             labels: {
                                                 format: '{value} '
                                             }
                                         },
                                         yAxis: {
                                             title: {
                                                 text: null
                                             }
                                         },
                                         tooltip: {
                                             positioner: function () {
                                                 return {
                                                     x: this.chart.chartWidth - this.label.width, // right aligned
                                                     y: -6 // align to title
                                                 };
                                             },
                                             borderWidth: 0,
                                             backgroundColor: 'none',
                                             pointFormat: '{point.y}',
                                             headerFormat: '',
                                             shadow: false,
                                             style: {
                                                 fontSize: '14px'
                                             },
                                             valueDecimals: dataset.valueDecimals
                                         },
                                         series: [{
                                             data: dataset.data,
                                             name: dataset.name,
                                             type: dataset.type,
                                             color: Highcharts.getOptions().colors[i],
                                             fillOpacity: 0.3,
                                             tooltip: {
                                                 valueSuffix: ' ' + dataset.unit
                                             }
                                         }]
                                     });
                             });
                         });
                }
            //--------------------------------------
        });


    </script>
}